
barney = [

    "                                      pppppppppppppp",
    "                                     ppppppp  pppppppppppp",
    "                                   ppppp              pppppp",
    "                                 ppppp       ppppp    ppppppp",
    "                               ppppp        pppxxpp  pppxxpppp",
    "                             ppppp           ppppp    pppppppppp",
    "                           pppp                       ppp ppppppppppp",
    "                           pppp                             pppppp pppp ppp",
    "               ppp         ppp            p                  ppppp  pppppppp",
    "              ppppp        ppp         pppppp                  pppp   pppppp",
    "     ppppppppppppppp       ppp         ppppppp                 ppppp   pppp",
    "    pppppppppppppppp       pppp            ppppp               pppppp ppp",
    "    pppp          ppp       pppp            pp ppppppp          pppp  ppp",
    "     pppppp        pppp      ppppp           pp  pppppp     ppppppp  ppp",
    "      pppppp       ppppp    ppppppp          pppppppppppppppppp     ppp",
    "          ppppp       ppppp  ppppp pppp       pppppppppppppppppp    ppp",
    "            ppppp      ppppppppppppppppppppp    ppppppppppppppp     ppp",
    "              ppppp       pppppppppppppppppppp    pppppppppppp     ppp",
    "  pppppppppppppppppp         ppp pppppppppppppppppppppppppppp     ppp",
    "ppppppppppppppppppp pp               pppppppp ppppppppppppppppp   pppp",
    "pp             ppppppp                pp    pppppppppp pppppp pppp",
    "pppppppp           pppppp             ppp    ppppppppppppppppppppp",
    "    pppppp           pppppp          pp       ppppp      pppppp",
    "       pppp           pppppppp      pp                    ppp",
    "         ppp         pppp  ppp     pp                      pp",
    "          ppp        ppp          pp                        pp",
    "          ppp       ppp           p                          pp",
    "           ppp     ppp           pp                           pp",
    "           ppp     ppp           pp                           pp",
    "            ppp   ppp            pp                            pp",
    "            ppp   ppp            pp                             p",
    "             ppp  pp              pp                            p",
    "             pppp pp              ppp                           p",
    "              ppppppp              pp                           p",
    "               ppppppp              pp                          pp",
    "                ppp ppp              ppp                       pppp",
    "                  pppppp              ppp                     pp ppp",
    "                     pppp              ppp                   pp  pppp",
    "                      pppp               pp                ppp    ppp",
    "                       ppppp              pp             ppp      ppp",
    "                       pppppppp            p          ppppp       ppp",
    "              pppppppppppp pppppp          p       ppppp          ppp",
    "             ppppp  ppp        pp        pppppppppppp            ppp",
    "            ppp                         pppppp    ppp           ppp",
    "            ppp                       pppp         ppp         ppp",
    "            ppp         pppp     pppppppp          ppp        pppp",
    "            ppp         pppppppppppppp           ppppp       ppppppp",
    "            ppp          ppppppp                 pppp            ppppppp",
    "             ppp    pp   ppppp                   ppp               ppppppp",
    "             ppp  ppppppppppppp                  pppp              pp pppp",
    "              ppppppp ppp  ppp                    ppppp       pppppppp ppp",
    "               pppppppppppppp                       pppppp   ppppppppppp",
    "                ppppp  pp                              ppppppppppppppp",
    "                                                          pppppppp",
]

tree = [
    "       y       ",
    "       g       ",
    "      ggg      ",
    "     grggg     ",
    "    gggbgrg    ",
    "   ggygrggog   ",
    "  ggrggbgygog  ",
    "      BBB      "]

smiley = ["     bbbbbbbb",
          "    byyyyyyyyb",
          "   byyyyyyyyyyb",
          "  byybyyyyyybyyb",
          "  byyyyyyyyyyyyb",
          "  byybyyyyyybyyb",
          "   byybbbbbbyyb",
          "    byyyyyyyyb",
          "     bbbbbbbb"]

donut = ["     bbbbbbbb",
         "    byyyyyyyyb",
         "   byyyyyyyyyyb",
         "  byybyy  yybyyb",
         "  byyyyy  yyyyyb",
         "  byybyy  yybyyb",
         "   byybbbbbbyyb",
         "    byyyyyyyyb",
         "     bbbbbbbb"]

life_saver = ["     bbbbbbbb",
             "    byy    yyb",
             "   byy      yyb",
             "  byy        yyb",
             "  byy        yyb",
             "  byy        yyb",
             "   byy      yyb",
             "    byy    yyb",
             "     bbbbbbbb"]

santa = [
    "                   rrrrrrr",
    "                  rr     rrrr",
    "                rrrr       rrrr",
    "               rr   r      r  r",
    "              r      r     r  r",
    "             r        rr   r  r",
    "            r           rr r  r",
    "           r            e ee  r",
    "          rr            eeee  r",
    "          rr                  rr",
    "         eeeeeeeeeeeeeeeeeeeeeeeeee",
    "         e   eee                e",
    "         e                      e",
    "         eeeeeeeeeeeeeeeeeeeeeeeee",
    "         e       exe  exe       e",
    "         e     P ebe  ebe P     e",
    "         e  e PPP   PP   PPP e  e",
    "         e  eeeeee PPPP eeeeee  e",
    "        e   e   eee PP       e   e",
    "       e     eeeeeeeyyeeeeeee     ee",
    "      e             PP             e",
    "      e                            e",
    "      e                            e",
    "      e                            e",
    "       e                          e",
    "        ee                      ee",
    "          eeeee            eeeee",
    "               eeeeeeeeeeeeee"]


batman = [

"      _==/          i     i          X==_",
"     /XX/            |X___/|            XXXX",
"   /XXXXX            |XXXXX|            /XXXXX",
"  |XXXXXXX_         _XXXXXXX_         _/XXXXXX|",
" XXXXXXXXXXXxxxxxxxXXXXXXXXXXXxxxxxxxXXXXXXXXXXX",
"|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"|XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX|",
' XXXXXX/^^^^"XXXXXXXXXXXXXXXXXXXXXX/^^^^^XXXXXXX',
"  |XXX|       XXXX/^^XXXXXX/^^XXXX/       |XXX|",
"    XXXX       XX/    XXXX/    XX/       /XX/",
'       "X       "      XX/      "      /"'
]